{{-- Generated by SKYmanager at {{ $generatedAt }}. Standalone — no CDN required. --}}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<title>{{ $wifiName }} – WiFi Portal</title>
<style>
/* ══ Reset ══════════════════════════════════════════════════════════════════ */
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html{-webkit-text-size-adjust:100%}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;
     background:#f0f9ff;min-height:100vh;color:#1e293b;line-height:1.5}
button{cursor:pointer;font-family:inherit;border:none;background:none}
input{font-family:inherit}

/* ══ Layout ═════════════════════════════════════════════════════════════════ */
.page{display:flex;flex-direction:column;min-height:100vh}

.header{background:linear-gradient(135deg,#0ea5e9 0%,#0284c7 100%);
        padding:20px 16px 24px;text-align:center;position:relative}
.header::after{content:'';position:absolute;bottom:-16px;left:0;right:0;height:32px;
               background:#f0f9ff;border-radius:50% 50% 0 0/100% 100% 0 0}

.wifi-icon{display:inline-flex;align-items:center;justify-content:center;
           width:56px;height:56px;background:rgba(255,255,255,.18);
           border-radius:16px;margin-bottom:10px}
.wifi-icon svg{width:32px;height:32px;fill:none;stroke:#fff;stroke-width:2;
               stroke-linecap:round;stroke-linejoin:round}

.header-title{font-size:20px;font-weight:700;color:#fff;letter-spacing:-.3px}
.header-sub{font-size:13px;color:rgba(255,255,255,.8);margin-top:2px}

.container{flex:1;max-width:480px;width:100%;margin:0 auto;padding:32px 16px 24px}

/* ══ Sections ═══════════════════════════════════════════════════════════════ */
.section{display:none}
.section.active{display:block}

/* ══ Plans grid ═════════════════════════════════════════════════════════════ */
.plans-heading{font-size:15px;font-weight:600;color:#0f172a;margin-bottom:14px}

.plans-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
@media(max-width:360px){.plans-grid{grid-template-columns:1fr}}

.plan-card{background:#fff;border:1.5px solid #e2e8f0;border-radius:16px;
           padding:16px;cursor:pointer;transition:all .18s ease;
           display:flex;flex-direction:column;gap:8px}
.plan-card:hover,.plan-card:active{border-color:#0ea5e9;background:#f0f9ff;
                                   transform:translateY(-1px);
                                   box-shadow:0 4px 16px rgba(14,165,233,.12)}

.plan-name{font-size:13px;font-weight:600;color:#0f172a;line-height:1.3}
.plan-price{font-size:22px;font-weight:800;color:#0ea5e9;letter-spacing:-.5px}
.plan-currency{font-size:11px;font-weight:600;color:#64748b;vertical-align:super;
               margin-right:1px}
.plan-tags{display:flex;flex-wrap:wrap;gap:4px}
.tag{display:inline-flex;align-items:center;gap:3px;padding:3px 7px;
     border-radius:99px;background:#f1f5f9;font-size:11px;font-weight:500;color:#475569}
.tag.speed{background:#ecfdf5;color:#059669}
.plan-desc{font-size:11px;color:#94a3b8;line-height:1.4;margin-top:2px}

/* ══ Phone entry ════════════════════════════════════════════════════════════ */
.selected-plan-badge{background:#0ea5e9;border-radius:12px;padding:14px 16px;
                     margin-bottom:20px;display:flex;align-items:center;gap:12px}
.selected-plan-badge .ps-name{font-size:14px;font-weight:600;color:#fff;flex:1}
.selected-plan-badge .ps-price{font-size:16px;font-weight:800;color:#fff}

.form-group{margin-bottom:16px}
.form-label{display:block;font-size:13px;font-weight:600;color:#374151;margin-bottom:6px}
.phone-prefix{display:flex;align-items:center;border:1.5px solid #e2e8f0;
              border-radius:12px;overflow:hidden;background:#fff;
              transition:border-color .15s}
.phone-prefix:focus-within{border-color:#0ea5e9;box-shadow:0 0 0 3px rgba(14,165,233,.12)}
.prefix-flag{padding:10px 12px;font-size:15px;background:#f8fafc;
             border-right:1.5px solid #e2e8f0;white-space:nowrap;
             font-size:13px;font-weight:600;color:#64748b}
.phone-input{flex:1;padding:10px 12px;border:none;outline:none;
             font-size:16px;color:#0f172a;background:transparent}

/* ══ Buttons ════════════════════════════════════════════════════════════════ */
.btn{display:flex;align-items:center;justify-content:center;gap:8px;
     width:100%;padding:13px 20px;border-radius:12px;font-size:15px;font-weight:600;
     transition:all .18s ease;letter-spacing:-.2px}
.btn-primary{background:#0ea5e9;color:#fff;box-shadow:0 2px 8px rgba(14,165,233,.25)}
.btn-primary:hover{background:#0284c7;box-shadow:0 4px 16px rgba(14,165,233,.35)}
.btn-primary:active{transform:scale(.98)}
.btn-primary:disabled{background:#93c5fd;box-shadow:none;cursor:not-allowed}
.btn-ghost{background:#f1f5f9;color:#475569}
.btn-ghost:hover{background:#e2e8f0}
.btn-success{background:#10b981;color:#fff;box-shadow:0 2px 8px rgba(16,185,129,.25)}
.btn-success:hover{background:#059669}
.btn-danger{background:#ef4444;color:#fff}

.btn-back{display:inline-flex;align-items:center;gap:4px;font-size:13px;
          font-weight:500;color:#64748b;background:none;padding:0;
          margin-bottom:16px}
.btn-back:hover{color:#0ea5e9}
.btn-back svg{width:14px;height:14px;stroke:currentColor;stroke-width:2;fill:none}

/* ══ Paying state ═══════════════════════════════════════════════════════════ */
.paying-card{background:#fff;border-radius:20px;padding:28px 24px;text-align:center;
             box-shadow:0 4px 24px rgba(0,0,0,.06)}
.spinner{width:48px;height:48px;border:4px solid #e2e8f0;border-top-color:#0ea5e9;
         border-radius:50%;animation:spin 1s linear infinite;margin:0 auto 16px}
@keyframes spin{to{transform:rotate(360deg)}}
.paying-title{font-size:17px;font-weight:700;color:#0f172a;margin-bottom:6px}
.paying-sub{font-size:13px;color:#64748b;line-height:1.5}
.paying-steps{text-align:left;margin-top:20px;space-y:10px}
.step{display:flex;align-items:center;gap:10px;padding:10px 12px;
      background:#f8fafc;border-radius:10px;margin-bottom:8px}
.step-num{width:22px;height:22px;border-radius:50%;background:#0ea5e9;
          color:#fff;font-size:11px;font-weight:700;display:flex;
          align-items:center;justify-content:center;flex-shrink:0}
.step-text{font-size:13px;color:#374151;font-weight:500}
.ussd-badge{background:#fef3c7;border:1px solid #fde68a;border-radius:10px;
            padding:10px 14px;margin-top:12px;font-size:12px;color:#92400e;
            font-weight:500;text-align:left}

/* ══ Success state ═══════════════════════════════════════════════════════════ */
.success-icon{width:68px;height:68px;border-radius:50%;background:#dcfce7;
              display:flex;align-items:center;justify-content:center;
              margin:0 auto 16px}
.success-icon svg{width:36px;height:36px;stroke:#10b981;stroke-width:2.5;fill:none}
.result-card{background:#fff;border-radius:20px;padding:28px 24px;text-align:center;
             box-shadow:0 4px 24px rgba(0,0,0,.06)}
.result-title{font-size:20px;font-weight:800;color:#0f172a;margin-bottom:6px}
.result-sub{font-size:13px;color:#64748b;line-height:1.5;margin-bottom:20px}
.countdown{font-size:12px;color:#94a3b8;margin-top:12px}

/* ══ Failed state ════════════════════════════════════════════════════════════ */
.failed-icon{width:68px;height:68px;border-radius:50%;background:#fee2e2;
             display:flex;align-items:center;justify-content:center;
             margin:0 auto 16px}
.failed-icon svg{width:36px;height:36px;stroke:#ef4444;stroke-width:2.5;fill:none}

/* ══ Loading state ═══════════════════════════════════════════════════════════ */
.loading-card{background:#fff;border-radius:20px;padding:40px 24px;text-align:center;
              box-shadow:0 4px 24px rgba(0,0,0,.06)}
.loading-dots{display:flex;justify-content:center;gap:8px;margin:0 auto 16px}
.dot{width:10px;height:10px;border-radius:50%;background:#0ea5e9;
     animation:pulse 1.4s ease-in-out infinite}
.dot:nth-child(2){animation-delay:.2s}
.dot:nth-child(3){animation-delay:.4s}
@keyframes pulse{0%,80%,100%{transform:scale(.6);opacity:.5}40%{transform:scale(1);opacity:1}}

/* ══ No plans ════════════════════════════════════════════════════════════════ */
.empty-card{background:#fff;border-radius:20px;padding:40px 24px;text-align:center;
            box-shadow:0 4px 24px rgba(0,0,0,.06)}
.empty-icon{width:56px;height:56px;border-radius:50%;background:#f1f5f9;
            display:flex;align-items:center;justify-content:center;margin:0 auto 14px}
.empty-icon svg{width:28px;height:28px;stroke:#94a3b8;stroke-width:2;fill:none}

/* ══ Tabs ════════════════════════════════════════════════════════════════════ */
.tab-bar{display:flex;background:#f1f5f9;border-radius:12px;padding:4px;gap:4px;margin-bottom:18px}
.tab-btn{flex:1;padding:8px 12px;border-radius:9px;font-size:13px;font-weight:600;
         color:#64748b;background:none;transition:all .15s ease;cursor:pointer}
.tab-btn.active{background:#fff;color:#0ea5e9;box-shadow:0 1px 6px rgba(0,0,0,.08)}
.tab-btn:hover:not(.active){color:#0f172a}

/* ══ Voucher section ════════════════════════════════════════════════════════ */
.voucher-input{width:100%;padding:12px 14px;border:1.5px solid #e2e8f0;
               border-radius:12px;font-size:16px;color:#0f172a;background:#fff;
               outline:none;transition:border-color .15s;
               text-transform:uppercase;letter-spacing:.05em;font-weight:600}
.voucher-input:focus{border-color:#0ea5e9;box-shadow:0 0 0 3px rgba(14,165,233,.12)}
.voucher-input.has-error{border-color:#ef4444}
.voucher-hint{font-size:11px;color:#94a3b8;margin-top:6px;line-height:1.5}
.voucher-error{display:none;margin-top:10px;padding:10px 14px;border-radius:10px;
               background:#fee2e2;border:1px solid #fca5a5;
               font-size:13px;font-weight:500;color:#991b1b;line-height:1.4}

/* ══ Button loading spinner ══════════════════════════════════════════════════ */
.btn-spinner{width:17px;height:17px;border:2.5px solid rgba(255,255,255,.4);
             border-top-color:#fff;border-radius:50%;animation:spin .7s linear infinite;
             flex-shrink:0}

/* ══ Countdown progress bar ═════════════════════════════════════════════════ */
.countdown-bar-wrap{height:4px;background:#e2e8f0;border-radius:99px;
                    margin-top:14px;overflow:hidden}
.countdown-bar{height:4px;background:#10b981;border-radius:99px;
               transition:width 1s linear;width:100%}

/* ══ Success plan badge ══════════════════════════════════════════════════════ */
.success-plan-badge{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;
                    padding:12px 16px;margin-bottom:16px;text-align:left}
.success-plan-badge .spb-label{font-size:11px;font-weight:700;color:#166534;
                                text-transform:uppercase;letter-spacing:.06em;
                                margin-bottom:3px}
.success-plan-badge .spb-name{font-size:15px;font-weight:700;color:#14532d}

/* ══ Footer ══════════════════════════════════════════════════════════════════ */
.footer{text-align:center;padding:20px 16px;font-size:11px;color:#94a3b8}
.footer a{color:#0ea5e9;text-decoration:none}
</style>
</head>
<body>
<div class="page">

  <!-- Header -->
  <div class="header">
    <div class="wifi-icon">
      <svg viewBox="0 0 24 24"><path d="M1.5 8.5C5.2 4.8 10.3 2.5 12 2.5s6.8 2.3 10.5 6M5 12c1.9-1.9 4.3-3 7-3s5.1 1.1 7 3M8.5 15.5c.9-.9 2.2-1.5 3.5-1.5s2.6.6 3.5 1.5M12 19h.01"/></svg>
    </div>
    <div class="header-title">{{ $wifiName }}</div>
    @if($companyName && $companyName !== $wifiName)
    <div class="header-sub" style="opacity:.9;margin-top:1px">{{ $companyName }}</div>
    @endif
    <div class="header-sub">Buy a data bundle to get online</div>
  </div>

  <!-- Main content -->
  <div class="container">

    <!-- Loading -->
    <div id="sec-loading" class="section active">
      <div class="loading-card">
        <div class="loading-dots"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>
        <div style="font-size:15px;font-weight:600;color:#0f172a">Loading packages…</div>
        <div style="font-size:13px;color:#64748b;margin-top:4px">Please wait a moment</div>
      </div>
    </div>

    <!-- No plans -->
    <div id="sec-no-plans" class="section">
      <div class="empty-card">
        <div class="empty-icon">
          <svg viewBox="0 0 24 24"><path d="M9.172 14.828L12 12m0 0l2.828-2.828M12 12L9.172 9.172M12 12l2.828 2.828M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z"/></svg>
        </div>
        <div style="font-size:16px;font-weight:700;color:#0f172a;margin-bottom:6px">No packages available</div>
        <div style="font-size:13px;color:#64748b;line-height:1.5">
          Contact the WiFi provider to set up payment packages.
        </div>
      </div>
    </div>

    <!-- Tab bar — shown above plans and voucher -->
    <div id="tab-bar" class="tab-bar" style="display:none">
      <button class="tab-btn active" id="tab-pay"     onclick="switchTab('pay')">💳 Buy Data</button>
      <button class="tab-btn"        id="tab-voucher" onclick="switchTab('voucher')">🎫 Voucher Code</button>
    </div>

    <!-- Plans -->
    <div id="sec-plans" class="section">
      <div class="plans-heading">Choose a package to get started</div>
      <div class="plans-grid" id="plansList"></div>
    </div>

    <!-- Voucher -->
    <div id="sec-voucher" class="section">
      <div class="form-group">
        <label class="form-label">Enter Your Voucher Code</label>
        <input class="voucher-input" type="text" id="voucherInput"
               placeholder="e.g. SKY-ABCD1234"
               maxlength="32" autocomplete="off" autocorrect="off" spellcheck="false"
               oninput="clearVoucherError()">
        <div class="voucher-hint">Enter the code exactly as printed on your voucher card. Codes are not case-sensitive.</div>
        <div class="voucher-error" id="voucherError"></div>
      </div>
      <button class="btn btn-primary" id="voucherBtn" onclick="submitVoucher()">
        <span id="voucherBtnText">🎫 Redeem Voucher</span>
        <span id="voucherBtnSpinner" style="display:none;align-items:center;gap:8px">
          <span class="btn-spinner"></span>Checking…
        </span>
      </button>
    </div>

    <!-- Phone entry -->
    <div id="sec-phone" class="section">
      <button class="btn-back" onclick="showSection('sec-plans')">
        <svg viewBox="0 0 24 24"><path d="M19 12H5m0 0l7 7m-7-7l7-7"/></svg>
        Back to packages
      </button>
      <div class="selected-plan-badge">
        <div>
          <div style="font-size:11px;color:rgba(255,255,255,.75);font-weight:500;margin-bottom:2px">SELECTED PACKAGE</div>
          <div class="ps-name" id="psName"></div>
        </div>
        <div class="ps-price" id="psPrice"></div>
      </div>
      <div class="form-group">
        <label class="form-label">Mobile Money Phone Number</label>
        <div class="phone-prefix">
          <div class="prefix-flag">🇹🇿 +255</div>
          <input class="phone-input" type="tel" id="phoneInput" inputmode="numeric"
                 pattern="[0-9]*" maxlength="10"
                 placeholder="712 345 678">
        </div>
        <div style="font-size:12px;color:#94a3b8;margin-top:6px">You will receive a USSD prompt — enter your PIN to confirm</div>
        <div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:10px">
          <span style="display:inline-flex;align-items:center;gap:4px;padding:4px 8px;border-radius:99px;background:#fef3c7;border:1px solid #fde68a;font-size:11px;font-weight:600;color:#92400e">📱 M-Pesa</span>
          <span style="display:inline-flex;align-items:center;gap:4px;padding:4px 8px;border-radius:99px;background:#ecfdf5;border:1px solid #a7f3d0;font-size:11px;font-weight:600;color:#065f46">📱 Tigo Pesa</span>
          <span style="display:inline-flex;align-items:center;gap:4px;padding:4px 8px;border-radius:99px;background:#eff6ff;border:1px solid #bfdbfe;font-size:11px;font-weight:600;color:#1e40af">📱 Airtel Money</span>
          @if($hasCustomGateway)
          <span style="display:inline-flex;align-items:center;gap:4px;padding:4px 8px;border-radius:99px;background:#f5f3ff;border:1px solid #ddd6fe;font-size:11px;font-weight:600;color:#5b21b6">✓ {{ $companyName }}</span>
          @endif
        </div>
      </div>
      <button class="btn btn-primary" id="payBtn" onclick="submitPayment()">
        Pay Now — <span id="payBtnPrice"></span>
      </button>
    </div>

    <!-- Paying / waiting for USSD -->
    <div id="sec-paying" class="section">
      <div class="paying-card">
        <div class="spinner"></div>
        <div class="paying-title">Waiting for payment…</div>
        <div class="paying-sub">Check your phone for a USSD pop-up and enter your PIN to confirm</div>
        <div class="paying-steps">
          <div class="step"><div class="step-num">1</div><div class="step-text">USSD prompt appears on your phone</div></div>
          <div class="step"><div class="step-num">2</div><div class="step-text">Enter your mobile money PIN</div></div>
          <div class="step"><div class="step-num">3</div><div class="step-text">Internet access granted automatically</div></div>
        </div>
        <div class="ussd-badge">⚠ Do not close this page. Keep it open until connected.</div>
      </div>
    </div>

    <!-- Success -->
    <div id="sec-success" class="section">
      <div class="result-card">
        <div class="success-icon">
          <svg viewBox="0 0 24 24"><path d="M20 6L9 17l-5-5"/></svg>
        </div>
        <div class="result-title">Connected! 🎉</div>
        <div class="result-sub" id="successMsg">You are now connected to the internet.</div>
        <div class="success-plan-badge" id="successPlanBadge" style="display:none">
          <div class="spb-label">Active Plan</div>
          <div class="spb-name" id="successPlanName"></div>
        </div>
        <button class="btn btn-success" onclick="startBrowsing()">
          Start Browsing →
        </button>
        <div class="countdown" id="countdown">Redirecting in <strong><span id="countdownSec">5</span>s</strong>…</div>
        <div class="countdown-bar-wrap"><div class="countdown-bar" id="countdownBar"></div></div>
      </div>
    </div>

    <!-- Failed -->
    <div id="sec-failed" class="section">
      <div class="result-card">
        <div class="failed-icon">
          <svg viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12"/></svg>
        </div>
        <div class="result-title">Payment Failed</div>
        <div class="result-sub" id="failedMsg">The payment was not completed. Please try again.</div>
        <button class="btn btn-primary" onclick="retryPayment()">Try Again</button>
      </div>
    </div>

  </div><!-- /.container -->

  <div class="footer">
    {{ $companyName }} WiFi &bull; Powered by <a href="#">SKYmanager</a> &bull; &copy; {{ date('Y') }}<br>
    <span style="font-size:10px;color:#cbd5e1">Build {{ $portalBuild ?? '—' }} · Generated {{ $generatedAt }}</span>
  </div>
</div>

@if(!empty($bundleMode))
<script src="md5.js"></script>
@endif
<script>
// ── Embedded constants (set at generation time) ───────────────────────────────
var VPS_URL   = '{{ $vpsUrl }}';
var ROUTER_ID = '{{ $routerId }}';
var PORTAL_TOKEN = @json($portalToken ?? '');
var PORTAL_BUILD = @json($portalBuild ?? '');

// ── Plans: embedded at generation time (no API call needed) ───────────────────
var PLANS = {!! $plansJson !!};

// ── MikroTik macros — MikroTik expands these when serving the file to clients ─
// When MikroTik serves this file, it replaces:
//   $(mac)             → client device MAC  e.g. "AA:BB:CC:DD:EE:FF"
//   $(ip)              → client device IP   e.g. "192.168.88.10"
//   $(link-login-only) → hotspot login URL  e.g. "http://192.168.88.1/login"
//   $(link-orig)       → original URL the user was visiting
var USER_MAC  = '$(mac)';
var USER_IP   = '$(ip)';
var LOGIN_URL = '$(link-login-only)';
var ORIG_URL  = '$(link-orig)';

// ── API endpoints on VPS (all in walled garden) ───────────────────────────────
var API = {
  session:   VPS_URL + '/api/local-portal/session/start',
  initiate:  VPS_URL + '/api/local-portal/payment/initiate',
  status:    VPS_URL + '/api/local-portal/payment/status/',
  authorize: VPS_URL + '/api/local-portal/mikrotik/authorize',
  voucher:   VPS_URL + '/api/local-portal/voucher/redeem',
};

// ── App state ─────────────────────────────────────────────────────────────────
var selectedPlan  = null;
var pollInterval  = null;
var currentRef    = null;
var countdownTimer = null;

// ── Initialise ────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', function () {
  // Announce session to VPS (validates router, logs portal visit). Fire-and-forget.
  if (ROUTER_ID) {
    fetch(API.session, {
      method:  'POST',
      headers: jsonHeaders(),
      body:    JSON.stringify({ router_id: ROUTER_ID, mac: USER_MAC, ip: USER_IP })
    }).catch(function () { /* non-fatal */ });
  }

  if (PLANS && PLANS.length > 0) {
    renderPlans(PLANS);
    showSection('sec-plans');
    // Reveal tab bar now that plans exist (voucher tab always available)
    var tb = document.getElementById('tab-bar');
    if (tb) { tb.style.display = 'flex'; }
    switchTab('pay');
  } else {
    // No payment plans — go straight to voucher tab
    var tb = document.getElementById('tab-bar');
    if (tb) { tb.style.display = 'flex'; }
    switchTab('voucher');
  }
});

// ── UI helpers ────────────────────────────────────────────────────────────────
function showSection(id) {
  document.querySelectorAll('.section').forEach(function (s) { s.classList.remove('active'); });
  var el = document.getElementById(id);
  if (el) { el.classList.add('active'); }
}

function switchTab(tab) {
  var isPay     = tab === 'pay';
  var tabPay    = document.getElementById('tab-pay');
  var tabVoucher = document.getElementById('tab-voucher');
  if (tabPay)    { tabPay.classList.toggle('active', isPay); }
  if (tabVoucher){ tabVoucher.classList.toggle('active', !isPay); }
  if (isPay) {
    // Only show plans section if there are plans; otherwise no-plans
    showSection(PLANS && PLANS.length > 0 ? 'sec-plans' : 'sec-no-plans');
  } else {
    showSection('sec-voucher');
  }
}

// ── Render plans ──────────────────────────────────────────────────────────────
function renderPlans(plans) {
  var grid = document.getElementById('plansList');
  grid.innerHTML = '';
  plans.forEach(function (p) {
    var card = document.createElement('div');
    card.className = 'plan-card';
    card.innerHTML =
      '<div class="plan-name">' + esc(p.name) + '</div>' +
      '<div style="margin-bottom:4px">' +
        '<span class="plan-currency">TZS</span>' +
        '<span class="plan-price">' + fmt(p.price) + '</span>' +
      '</div>' +
      '<div class="plan-tags">' +
        '<span class="tag">' + esc(p.duration_label) + '</span>' +
        '<span class="tag speed">' + esc(p.speed_label) + '</span>' +
      '</div>' +
      (p.description ? '<div class="plan-desc">' + esc(p.description) + '</div>' : '');
    card.addEventListener('click', function () { selectPlan(p); });
    grid.appendChild(card);
  });
}

function selectPlan(plan) {
  selectedPlan = plan;
  document.getElementById('psName').textContent    = plan.name;
  document.getElementById('psPrice').textContent   = 'TZS ' + fmt(plan.price);
  document.getElementById('payBtnPrice').textContent = 'TZS ' + fmt(plan.price);
  document.getElementById('phoneInput').value      = '';
  showSection('sec-phone');
}

function retryPayment() {
  stopPolling();
  currentRef = null;
  switchTab('pay');
}

// ── Voucher redemption ────────────────────────────────────────────────────────
function clearVoucherError() {
  var inp = document.getElementById('voucherInput');
  var err = document.getElementById('voucherError');
  if (inp) { inp.classList.remove('has-error'); }
  if (err) { err.style.display = 'none'; err.textContent = ''; }
}

function showVoucherError(msg) {
  var inp = document.getElementById('voucherInput');
  var err = document.getElementById('voucherError');
  if (inp) { inp.classList.add('has-error'); }
  if (err) { err.textContent = '⚠ ' + msg; err.style.display = 'block'; }
}

function setVoucherLoading(loading) {
  var btn  = document.getElementById('voucherBtn');
  var txt  = document.getElementById('voucherBtnText');
  var spin = document.getElementById('voucherBtnSpinner');
  if (btn)  { btn.disabled = loading; }
  if (txt)  { txt.style.display  = loading ? 'none'         : 'inline'; }
  if (spin) { spin.style.display = loading ? 'inline-flex'  : 'none'; }
}

function submitVoucher() {
  clearVoucherError();
  var code = (document.getElementById('voucherInput').value || '').trim().toUpperCase();

  if (!code) {
    showVoucherError('Please enter a voucher code before redeeming.');
    return;
  }

  setVoucherLoading(true);

  fetch(API.voucher, {
    method:  'POST',
    headers: jsonHeaders(),
    body:    JSON.stringify({ router_id: ROUTER_ID, code: code, mac: USER_MAC, ip: USER_IP })
  })
  .then(okJson)
  .then(function (data) {
    setVoucherLoading(false);

    if (data.error) {
      showVoucherError(data.error);
      return;
    }

    if (data.status === 'authorized') {
      var msg = data.message || ('Voucher "' + esc(data.plan_name || code) + '" redeemed! You are connected.');
      document.getElementById('successMsg').textContent = msg;
      if (data.plan_name) {
        var badge = document.getElementById('successPlanBadge');
        var name  = document.getElementById('successPlanName');
        if (badge) { badge.style.display = 'block'; }
        if (name)  { name.textContent = data.plan_name
          + (data.duration_minutes ? ' · ' + fmtDuration(data.duration_minutes) : ''); }
      }
      onAuthorized();
    }
  })
  .catch(function (err) {
    setVoucherLoading(false);
    var detail = (err && err.message) ? err.message : 'Network error — please check your connection and try again.';
    showVoucherError(detail);
  });
}

// ── Payment initiation ────────────────────────────────────────────────────────
function submitPayment() {
  var rawPhone = document.getElementById('phoneInput').value.replace(/\D/g, '');

  if (rawPhone.length < 9) {
    alert('Please enter a valid phone number (e.g. 712 345 678).');
    return;
  }

  var phone = '255' + rawPhone.slice(-9);
  var btn   = document.getElementById('payBtn');
  btn.disabled    = true;
  btn.textContent = 'Sending USSD…';

  var body = {
    router_id: ROUTER_ID,
    plan_id:   selectedPlan.id,
    mac:       USER_MAC,
    ip:        USER_IP,
    phone:     phone
  };

  fetch(API.initiate, {
    method:  'POST',
    headers: jsonHeaders(),
    body:    JSON.stringify(body)
  })
  .then(okJson)
  .then(function (data) {
    btn.disabled    = false;
    btn.textContent = 'Pay Now — TZS ' + fmt(selectedPlan.price);

    if (data.error) { alert(data.error); return; }

    if (!data.reference) {
      alert('Payment initiation failed — no reference returned. Please try again.');
      return;
    }

    currentRef = data.reference;
    showSection('sec-paying');
    startPolling(currentRef);
  })
  .catch(function (err) {
    btn.disabled    = false;
    btn.textContent = 'Pay Now — TZS ' + fmt(selectedPlan.price);
    var detail = (err && err.message) ? err.message : 'Request failed — check Wi‑Fi and try again.';
    alert(detail);
  });
}

// ── Status polling ────────────────────────────────────────────────────────────
function startPolling(reference) {
  if (!reference || reference === 'undefined') { return; }
  stopPolling();
  var attempts = 0;
  var maxAttempts = 60; // 3 min at 3 s intervals

  pollInterval = setInterval(function () {
    attempts++;

    if (attempts > maxAttempts) {
      stopPolling();
      document.getElementById('failedMsg').textContent =
        'Payment timed out. If money was deducted, please contact the WiFi provider.';
      showSection('sec-failed');
      return;
    }

    fetch(API.status + encodeURIComponent(reference), {
      headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' }
    })
    .then(okJson)
    .then(function (data) {
      if (data.status === 'authorized') {
        stopPolling();
        onAuthorized();
      } else if (data.status === 'success') {
        // Payment confirmed but MikroTik auth not yet done — call explicit endpoint
        callAuthorize(reference);
      } else if (data.status === 'failed') {
        stopPolling();
        document.getElementById('failedMsg').textContent =
          data.message || 'Payment was not completed. Please try again.';
        showSection('sec-failed');
      }
      // 'pending' → keep polling
    })
    .catch(function () { /* network hiccup — retry next cycle */ });
  }, 3000);
}

function stopPolling() {
  if (pollInterval) { clearInterval(pollInterval); pollInterval = null; }
  if (countdownTimer) { clearInterval(countdownTimer); countdownTimer = null; }
}

// ── Explicit authorize fallback ───────────────────────────────────────────────
function callAuthorize(reference) {
  fetch(API.authorize, {
    method:  'POST',
    headers: jsonHeaders(),
    body:    JSON.stringify({ reference: reference })
  })
  .then(okJson)
  .then(function (data) {
    if (data.status === 'authorized') {
      stopPolling();
      onAuthorized();
    }
  })
  .catch(function () { /* non-fatal — polling retries */ });
}

// ── Authorized: success screen + countdown ────────────────────────────────────
function onAuthorized() {
  if (selectedPlan) {
    document.getElementById('successMsg').textContent =
      'Payment confirmed! Enjoy your ' + selectedPlan.name + '.';
    var badge = document.getElementById('successPlanBadge');
    var name  = document.getElementById('successPlanName');
    if (badge) { badge.style.display = 'block'; }
    if (name)  {
      name.textContent = selectedPlan.name + ' — TZS ' + fmt(selectedPlan.price)
        + ' · ' + esc(selectedPlan.duration_label || '');
    }
  }
  showSection('sec-success');

  var total = 5;
  var secs  = total;
  document.getElementById('countdownSec').textContent = secs;
  var bar = document.getElementById('countdownBar');
  if (bar) { bar.style.width = '100%'; }

  countdownTimer = setInterval(function () {
    secs--;
    var el = document.getElementById('countdownSec');
    if (el) { el.textContent = secs; }
    if (bar) { bar.style.width = Math.max(0, (secs / total) * 100) + '%'; }
    if (secs <= 0) {
      clearInterval(countdownTimer);
      startBrowsing();
    }
  }, 1000);
}

// ── Navigate to internet after MikroTik grants access ─────────────────────────
function startBrowsing() {
  stopPolling();
  var isMacro = function (v) { return !v || v.indexOf('$(') === 0; };

  if (isMacro(LOGIN_URL)) {
    // Running in a browser outside MikroTik context — just reload
    window.location.reload();
    return;
  }

  var dst = !isMacro(ORIG_URL) ? ORIG_URL : 'http://www.google.com';
  // MikroTik login endpoint: MAC binding auto-authenticates the device
  window.location.href = LOGIN_URL + '?dst=' + encodeURIComponent(dst);
}

// ── Shared helpers ─────────────────────────────────────────────────────────────
function jsonHeaders() {
  var h = {
    'Content-Type':     'application/json',
    'Accept':           'application/json',
    'X-Requested-With': 'XMLHttpRequest'
  };
  if (PORTAL_TOKEN) {
    h['X-SKY-Portal-Token'] = PORTAL_TOKEN;
  }
  return h;
}

function okJson(r) {
  return r.json().then(function (body) {
    if (!r.ok) {
      throw new Error(body.error || body.message || ('Request failed (' + r.status + ')'));
    }
    return body;
  });
}

function esc(str) {
  return String(str || '')
    .replace(/&/g,'&amp;').replace(/</g,'&lt;')
    .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function fmt(n) {
  return Number(n).toLocaleString('en-US', { maximumFractionDigits: 0 });
}

function fmtDuration(minutes) {
  if (!minutes) { return ''; }
  if (minutes >= 1440 && minutes % 1440 === 0) { return (minutes / 1440) + (minutes === 1440 ? ' Day' : ' Days'); }
  if (minutes >= 60   && minutes % 60   === 0) { return (minutes / 60)   + (minutes === 60   ? ' Hour' : ' Hours'); }
  return minutes + ' Min';
}
</script>
</body>
</html>
