<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Router;
use App\Services\StandalonePortalHtmlService;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class PortalHtmlController extends Controller
{
    /**
     * GET /customer/plans/download-login-html/{routerId}?signature=…&expires=…
     *
     * Generates a completely self-contained login.html and streams it as a file
     * download. Requires a valid temporary signed URL (15 min) generated by the
     * Livewire component. Only the router's owner may download.
     */
    public function download(string $routerId, StandalonePortalHtmlService $service): Response
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This download link has expired. Please go back to My Plans and generate a new one.');
        }

        $router = Router::findOrFail($routerId);

        if ($router->user_id !== Auth::id()) {
            abort(403, 'You do not own this router.');
        }

        $html = $service->generateForRouter($router, Auth::user());

        $slug = preg_replace('/[^a-z0-9]+/', '-', strtolower($router->hotspot_ssid ?: $router->name ?: 'router'));
        $slug = trim($slug, '-') ?: 'router';
        $filename = 'login-'.$slug.'.html';

        return response($html, 200, [
            'Content-Type' => 'text/html; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="'.$filename.'"',
            'Cache-Control' => 'no-store, no-cache',
        ]);
    }

    /**
     * GET /customer/plans/preview-login-html/{routerId}?signature=…&expires=…
     *
     * Returns the generated login.html as a viewable page (no download header).
     * Requires a valid temporary signed URL (15 min) generated by the Livewire
     * component. Opens in a new browser tab for instant preview.
     */
    public function preview(string $routerId, StandalonePortalHtmlService $service): Response
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This preview link has expired or is invalid. Please click "Preview" again from My Plans.');
        }

        $router = Router::findOrFail($routerId);

        if ($router->user_id !== Auth::id()) {
            abort(403, 'You do not own this router.');
        }

        $html = $service->generateForRouter($router, Auth::user());

        return response($html, 200, [
            'Content-Type' => 'text/html; charset=UTF-8',
            'Cache-Control' => 'no-store, no-cache',
            'X-Frame-Options' => 'SAMEORIGIN',
        ]);
    }
}
