<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Router;
use App\Services\HotspotBundleService;
use App\Services\StandalonePortalHtmlService;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class PortalHtmlController extends Controller
{
    /**
     * GET /customer/plans/download-login-html/{routerId}?signature=…&expires=…
     *
     * Streams a legacy self-contained HTML portal (single file). Prefer the hotspot
     * bundle + MikroTik script for full structure. Requires a valid temporary signed
     * URL (15 min) generated by the Livewire component. Only the router owner may download.
     */
    public function download(string $routerId, StandalonePortalHtmlService $service): Response
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This download link has expired. Please go back to My Plans and generate a new one.');
        }

        $router = Router::findOrFail($routerId);

        if ($router->user_id !== Auth::id()) {
            abort(403, 'You do not own this router.');
        }

        $router->ensureLocalPortalToken();
        app(HotspotBundleService::class)->syncBundleMetadata($router->fresh(), Auth::user());

        $html = $service->generateForRouter($router->fresh(), Auth::user());

        $slug = preg_replace('/[^a-z0-9]+/', '-', strtolower($router->hotspot_ssid ?: $router->name ?: 'router'));
        $slug = trim($slug, '-') ?: 'router';
        // Not named login.html so operators choose the full bundle + script path first; manual upload still uses login.html on the router.
        $filename = 'skymanager-legacy-single-file-'.$slug.'.html';

        return response($html, 200, [
            'Content-Type' => 'text/html; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="'.$filename.'"',
            'Cache-Control' => 'no-store, no-cache',
        ]);
    }

    /**
     * GET /customer/plans/preview-login-html/{routerId}?signature=…&expires=…
     *
     * Returns the generated login.html as a viewable page (no download header).
     * Requires a valid temporary signed URL (15 min) generated by the Livewire
     * component. Opens in a new browser tab for instant preview.
     */
    public function preview(string $routerId, StandalonePortalHtmlService $service): Response
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This preview link has expired or is invalid. Please click "Preview" again from My Plans.');
        }

        $router = Router::findOrFail($routerId);

        if ($router->user_id !== Auth::id()) {
            abort(403, 'You do not own this router.');
        }

        $router->ensureLocalPortalToken();
        app(HotspotBundleService::class)->syncBundleMetadata($router->fresh(), Auth::user());

        $html = $service->generateForRouter($router->fresh(), Auth::user());

        return response($html, 200, [
            'Content-Type' => 'text/html; charset=UTF-8',
            'Cache-Control' => 'no-store, no-cache',
            'X-Frame-Options' => 'SAMEORIGIN',
        ]);
    }

    /**
     * Owner-only hotspot bundle inspector (HTML files + manifest data).
     */
    public function bundleOverview(string $routerId, HotspotBundleService $bundles): View
    {
        $router = Router::findOrFail($routerId);

        if ($router->user_id !== Auth::id()) {
            abort(403, 'You do not own this router.');
        }

        $router->ensureLocalPortalToken();
        $bundles->syncBundleMetadata($router->fresh(), Auth::user());
        $router->refresh();

        $manifest = $bundles->manifestPayload($router, Auth::user(), refresh: false, compareLive: true);

        return view('customer.hotspot-bundle', [
            'router' => $router,
            'manifest' => $manifest,
        ]);
    }

    /**
     * Signed preview/download of one bundle file (same HTML/JS the router fetches).
     */
    public function bundleFile(string $routerId, string $file, HotspotBundleService $bundles): Response
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This link has expired. Regenerate it from the hotspot bundle page.');
        }

        $router = Router::findOrFail($routerId);

        if ($router->user_id !== Auth::id()) {
            abort(403, 'You do not own this router.');
        }

        if (! $bundles->isAllowedFile($file)) {
            abort(404);
        }

        $body = $bundles->renderFile($router, Auth::user(), $file);

        $contentType = str_ends_with($file, '.js')
            ? 'application/javascript; charset=UTF-8'
            : 'text/html; charset=UTF-8';

        $disposition = request()->boolean('download') ? 'attachment' : 'inline';
        $filename = 'skymanager-'.$file;

        return response($body, 200, [
            'Content-Type' => $contentType,
            'Content-Disposition' => $disposition.'; filename="'.$filename.'"',
            'Cache-Control' => 'no-store, no-cache',
            'X-Frame-Options' => 'SAMEORIGIN',
        ]);
    }
}
